### ISSUE TITLE
PyPI package for v0.4 is broken

### ISSUE THREAD

**Issue by mikenerone** [wronglink/pytest-pudb#6]
Earlier today, `HISTORY.rst` was added to the repo and version 0.4 was published to PyPI. `HISTORY.rst` is not included in published source package, leading to this error or similar during install:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vr/swfrp8952bxbpzk3fx3b1fyh0000gn/T/pip-build-gsinvzjt/pytest-pudb/setup.py", line 11, in <module>
        open('HISTORY.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
```

**Comment by wronglink** [comment]
@mikenerone sorry about that. I've forgotten to add `MANIFEST.in` file. Thanks for feedback!
